---
# Docker Compose 2.4 is for local development
# https://www.heroku.com/podcasts/codeish/57-discussing-docker-containers-and-kubernetes-with-a-docker-captain - Source on that.
version: '2.4'

services:
  app: &app
    image: pig-ci:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    command: >
      bash -c "bundle check || bundle install &&
      yarn install --check-files"
    environment:
      REDIS_URL: redis://@redis:6379/1
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/
      WEBPACKER_DEV_SERVER_HOST: webpacker
    volumes:
      - .:/usr/src/app
      - rails_cache:/usr/src/app/tmp/cache
      - bundle:/usr/local/bundle
      - packs:/usr/src/app/public/packs
      - node_modules:/usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:11.7-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  redis:
    image: redis:4.0.14-alpine
    command: >
      --save
      --maxmemory 128mb
      --maxmemory-policy noeviction
      --stop-writes-on-bgsave-error yes
      --rdbcompression yes
      --rdbchecksum yes
      --dir /data
    volumes:
      - redis:/data
    ports:
      - 6379
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  web:
    <<: *app
    command: bash -c "rm -rf /usr/src/app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"

  worker:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - '3035:3035'

volumes:
  postgres: 
  redis:
  rails_cache:
  bundle:
  node_modules:
  packs:
